# Generated by Django 5.2.4 on 2025-09-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('estatura', models.FloatField()),
                ('edad', models.IntegerField()),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
    ]
