# Generated by Django 5.2.5 on 2025-09-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "numeroConsulta",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("fecha", models.CharField(max_length=10)),
                ("nombreMedico", models.CharField(max_length=50)),
                ("deinpr", models.CharField(max_length=20)),
                ("procedencia", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "consulta",
                "managed": False,
            },
        ),
    ]
