-- SCRIPT ORACLE SQL: TABLAS_BD16052025.SQL 

-- ELIMINAR UN USUARIO CON TODOS SUS OBJETOS (TABLAS, VISTAS, SECUENCIAS ETC) DE PROPIEDAD DEL USUARIO
DROP USER BD16052025 CASCADE;

-- CREAR UN NUEVO USUARIO CON UNA CONTRASEÑA
CREATE USER BD16052025 IDENTIFIED BY 12345678;

-- EL ROL CONNECT PERMITE A UN USUARIO INICIAR SESION EN LA BASE DE DATOS
-- EL ROL RESOURCE PERMITE A UN USUARIO PERMISOS PARA CREAR Y MODIFICAR OBJETOS DE ESQUEMA, COMO TABLAS, VISTAS, SECUENCIAS ETC
-- EL ROL DBA OTORGA TODOS LOS PRIVILEGIOS ADMINISTRATIVOS A UN USUARIO
GRANT CONNECT,RESOURCE,DBA TO BD16052025;

-- ESTE PRIVILEGIO PERMITE AL USUARIO USAR UN ESPACIO ILIMITADO EN TODOS LOS TABLESPACES DE LA BASE DE DATOS
GRANT UNLIMITED TABLESPACE TO BD16052025;

-- MODIFICA EL PERFIL DEFAULT PARA QUE EL PARAMETRO PASSWORD_REUSE_TIME NO TENGA LIMITES. NO HAY RESTRICCIONES DE TIEMPO PARA LA REUTILIZACION DE CONTRASEÑAS
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;

-- MODIFICA EL PERFIL DEFAULT PARA QUE EL PARAMETRO PASSWORD_LIFE_TIME NO TENGA LIMITES. LA CONTRASEÑA NUNCA EXPIRA
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- DESBLOQUEAR AL USUARIO BD16052025 POR SI ESTUBIERA BLOQUEADO
ALTER USER BD16052025 ACCOUNT UNLOCK;

-- INICIAR SESION CON EL USUARIO BD16052025
CONNECT BD16052025/12345678@LOCALHOST:1521/XEPDB1

-- CONFIGURAR EL FORMATO DE LA FECHA, COMO DEBE SER INGRESADA EN INSERT
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD'; 

-- DESACTIVAR TEMPORALMENTE LA FUNCION DE SUSTITUCION DE VARIABLE EN TU SESION
SET DEFINE OFF;

-- 1. Crear una tabla

CREATE TABLE PERSONA (
    idPersona     NUMBER       GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Clave primaria autoincremental
    nombre        VARCHAR2(50)                         NOT NULL,        			 -- Texto
    edad          NUMBER(3)                            NOT NULL,                   	 -- Entero
    altura        FLOAT                                NOT NULL,                   	 -- Punto flotante
    casado        CHAR(1) CHECK (casado IN ('S', 'N')) NOT NULL,     		         -- Lógico ('S' o 'N')
    fecha_nac     DATE                                 NOT NULL                      -- Fecha
);

-- 2. Crear una secuencia para el campo autoincremental

CREATE SEQUENCE seq_persona
START WITH 1
INCREMENT BY 1
NOCACHE;

-- 3. Crear un trigger para autoincrementar idPersona

CREATE OR REPLACE TRIGGER trg_before_insert_persona
BEFORE INSERT ON PERSONA
FOR EACH ROW
BEGIN
    IF :new.idPersona IS NULL THEN
        SELECT seq_persona.NEXTVAL INTO :new.idPersona FROM dual;
    END IF;
END;
/

-- 4. Insertar un ejemplo de registro

INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Juan Pérez', 30, 1.75, 'S', TO_DATE('1994-05-16', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('María Gómez', 28, 1.65, 'N', TO_DATE('1996-03-10', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Carlos Ruiz', 35, 1.80, 'S', TO_DATE('1989-07-21', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Lucía Fernández', 22, 1.60, 'N', TO_DATE('2002-01-30', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Pedro Sánchez', 40, 1.78, 'S', TO_DATE('1984-12-05', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Ana Torres', 27, 1.68, 'N', TO_DATE('1997-08-15', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Luis Martínez', 31, 1.72, 'S', TO_DATE('1993-11-09', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Isabel Díaz', 45, 1.63, 'S', TO_DATE('1979-06-01', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Diego Romero', 19, 1.82, 'N', TO_DATE('2005-09-14', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Claudia Navarro', 33, 1.70, 'S', TO_DATE('1991-02-18', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('José Herrera', 29, 1.76, 'N', TO_DATE('1995-04-22', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Valeria Castro', 24, 1.61, 'N', TO_DATE('2000-07-30', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Andrés Molina', 36, 1.85, 'S', TO_DATE('1988-03-03', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Patricia León', 38, 1.66, 'S', TO_DATE('1986-12-28', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Hugo Paredes', 26, 1.79, 'N', TO_DATE('1998-05-11', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Sofía Ortega', 23, 1.58, 'N', TO_DATE('2001-10-05', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Manuel Cordero', 41, 1.74, 'S', TO_DATE('1983-09-17', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Gabriela Fuentes', 32, 1.67, 'S', TO_DATE('1992-06-09', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Ricardo Peña', 21, 1.81, 'N', TO_DATE('2003-08-22', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Marta Salas', 34, 1.62, 'S', TO_DATE('1990-04-12', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Fernando Ríos', 39, 1.77, 'S', TO_DATE('1985-02-02', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Camila Durán', 25, 1.64, 'N', TO_DATE('1999-01-19', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Tomás Aguilar', 37, 1.83, 'S', TO_DATE('1987-10-13', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Elena Ramos', 20, 1.59, 'N', TO_DATE('2004-12-07', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Iván Varela', 27, 1.71, 'N', TO_DATE('1997-11-26', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Natalia Jiménez', 31, 1.69, 'S', TO_DATE('1993-06-23', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Fabián Cabrera', 29, 1.84, 'N', TO_DATE('1995-05-09', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Laura Méndez', 26, 1.63, 'N', TO_DATE('1998-09-30', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Samuel Bravo', 42, 1.78, 'S', TO_DATE('1982-11-20', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Daniela Vega', 35, 1.60, 'S', TO_DATE('1989-02-27', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Esteban Sáenz', 33, 1.82, 'S', TO_DATE('1991-01-11', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Julieta Mora', 22, 1.57, 'N', TO_DATE('2002-06-06', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Benjamín Torres', 28, 1.76, 'N', TO_DATE('1996-07-03', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Ángela Suárez', 36, 1.68, 'S', TO_DATE('1988-08-18', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Adrián Lozano', 24, 1.70, 'N', TO_DATE('2000-05-01', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Noelia Medina', 30, 1.62, 'S', TO_DATE('1994-03-25', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Cristian Lara', 38, 1.79, 'S', TO_DATE('1986-04-14', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Silvia Barrios', 27, 1.61, 'N', TO_DATE('1997-10-28', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Matías Rojas', 23, 1.73, 'N', TO_DATE('2001-12-12', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Rocío Acosta', 32, 1.65, 'S', TO_DATE('1992-07-08', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Agustín Castillo', 40, 1.80, 'S', TO_DATE('1984-09-04', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Victoria Serrano', 34, 1.67, 'S', TO_DATE('1990-08-02', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Javier Salgado', 25, 1.75, 'N', TO_DATE('1999-11-06', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Paula Quintero', 28, 1.60, 'N', TO_DATE('1996-02-24', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Emilio Estrada', 39, 1.77, 'S', TO_DATE('1985-05-19', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Melina Guerra', 21, 1.59, 'N', TO_DATE('2003-03-16', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Leandro Vargas', 37, 1.83, 'S', TO_DATE('1987-06-30', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Antonia Herrera', 20, 1.62, 'N', TO_DATE('2004-01-02', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Sebastián Carrillo', 26, 1.74, 'N', TO_DATE('1998-08-19', 'YYYY-MM-DD'));
INSERT INTO PERSONA (nombre, edad, altura, casado, fecha_nac) VALUES ('Carmen Reyes', 33, 1.68, 'S', TO_DATE('1991-09-25', 'YYYY-MM-DD'));

