DROP USER INSTITUTO CASCADE;
CREATE USER INSTITUTO IDENTIFIED BY 12345678;
GRANT CONNECT,RESOURCE,dba TO INSTITUTO;
GRANT UNLIMITED TABLESPACE TO INSTITUTO;
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- INICIAR SESION CON EL USUARIO PROBANDO1
CONNECT INSTITUTO/12345678@LOCALHOST:1521/XEPDB1

-- CONFIGURAR EL FORMATO DE LA FECHA, COMO DEBE SER INGRESADA EN INSERT
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD'; 

CREATE TABLE ALUMNO (
   IDALUMNO       CHAR(4)      NOT NULL PRIMARY KEY,
   NOMBRE         VARCHAR2(20) NOT NULL,
   APELLIDO       VARCHAR2(40) NOT NULL,
   EDAD           NUMBER(3)    NOT NULL,
   ESTATURA       NUMBER(3,2)  NOT NULL,
   FECHAMATRICULA DATE         NOT NULL,
   SEXO           CHAR(1)      NOT NULL,
   ESCASADO       NUMBER(1,0)  NOT NULL CHECK (ESCASADO IN (0,1)) -- 1 representa verdadero, 0 representa falso
);

INSERT INTO ALUMNO (IDALUMNO,NOMBRE,APELLIDO,EDAD,ESTATURA,FECHAMATRICULA,SEXO,ESCASADO) VALUES ('A001','Luis','Ruiz',23,1.62,'2023-01-01','H',0);
INSERT INTO ALUMNO (IDALUMNO,NOMBRE,APELLIDO,EDAD,ESTATURA,FECHAMATRICULA,SEXO,ESCASADO) VALUES ('A002','Miguel','Roncal',22,1.72,'2023-01-02','H',1);
INSERT INTO ALUMNO (IDALUMNO,NOMBRE,APELLIDO,EDAD,ESTATURA,FECHAMATRICULA,SEXO,ESCASADO) VALUES ('A003','Carlos','Lescano',21,1.73,'2023-01-03','H',0);
INSERT INTO ALUMNO (IDALUMNO,NOMBRE,APELLIDO,EDAD,ESTATURA,FECHAMATRICULA,SEXO,ESCASADO) VALUES ('A004','Carmen','Alva',20,1.56,'2023-01-02','M',0);
INSERT INTO ALUMNO (IDALUMNO,NOMBRE,APELLIDO,EDAD,ESTATURA,FECHAMATRICULA,SEXO,ESCASADO) VALUES ('A005','María','Jauregui',22,1.68,'2023-01-02','M',1);
