# Generated by Django 5.2.5 on 2025-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("estatura", models.FloatField()),
            ],
            options={
                "db_table": ("alumno",),
                "managed": False,
            },
        ),
    ]
