DROP USER USUARIOJOIN CASCADE;
CREATE USER USUARIOJOIN IDENTIFIED BY 12345678;
GRANT CONNECT,RESOURCE,dba TO USUARIOJOIN;
GRANT UNLIMITED TABLESPACE TO USUARIOJOIN;
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- INICIAR SESION CON EL USUARIO PROBANDO1
CONNECT USUARIOJOIN/12345678@LOCALHOST:1521/XEPDB1

CREATE TABLE A(
   ID     NUMBER(1,0) NOT NULL PRIMARY KEY,
   NOMBRE CHAR(2)     NOT NULL
);

CREATE TABLE B(
   ID       NUMBER(1,0) NOT NULL PRIMARY KEY,
   APELLIDO CHAR(2)     NOT NULL
);

INSERT INTO A(ID, NOMBRE) VALUES (1, 'A1');
INSERT INTO A(ID, NOMBRE) VALUES (2, 'B1');
INSERT INTO A(ID, NOMBRE) VALUES (3, 'C1');
INSERT INTO A(ID, NOMBRE) VALUES (4, 'D1');
INSERT INTO A(ID, NOMBRE) VALUES (5, 'E1');

INSERT INTO B(ID, APELLIDO) VALUES (1, 'A2');
INSERT INTO B(ID, APELLIDO) VALUES (2, 'B2');
INSERT INTO B(ID, APELLIDO) VALUES (3, 'C2');
INSERT INTO B(ID, APELLIDO) VALUES (4, 'D2');
INSERT INTO B(ID, APELLIDO) VALUES (6, 'F2');


/*
-------
TABLA A
-------

ID	NOMBRE
1	A1
2	B1
3	C1
4	D1
5	E1

-------
TABLA B
-------

ID	APELLIDO
1	A2
2	B2
3	C2
4	D2
6	F2

-----------------------------
INNER JOIN (A INTERSECCION B)
-----------------------------

SELECT A.ID, A.NOMBRE, B.APELLIDO
FROM A
INNER JOIN B ON A.ID = B.ID;

SELECT B.ID, A.NOMBRE, B.APELLIDO
FROM A
INNER JOIN B ON A.ID = B.ID;

ID  NOMBRE		APELLIDO
1	A1			A2
2	B1			B2
3	C1			C2
4	D1			D2

--------------------------
LEFT JOIN (A DIFERENCIA B)
--------------------------

SELECT A.ID, A.NOMBRE, B.APELLIDO
FROM A
LEFT JOIN B ON A.ID = B.ID;

ID  NOMBRE		APELLIDO
1	A1			A2
2	B1			B2
3	C1			C2
4	D1			D2
5	E1			NULL

---------------------------
RIGHT JOIN (B DIFERENCIA A)
---------------------------

SELECT B.ID, A.NOMBRE, B.APELLIDO
FROM A
RIGHT JOIN B ON A.ID = B.ID;

ID  NOMBRE  APELLIDO
1	A1		A2
2	B1		B2
3	C1		C2
4	D1		D2
6	NULL	F2

----------------------
FULL JOIN  (B UNION B)      NO EXISTE EN ORACLE PERO SE PUEDE SIMULAR CON LEFT Y RIGHT
----------------------

SELECT A.ID, A.NOMBRE, B.APELLIDO
FROM A
LEFT JOIN B ON A.ID = B.ID
UNION
SELECT B.ID, A.NOMBRE, B.APELLIDO
FROM A
RIGHT JOIN B ON A.ID = B.ID
WHERE A.ID IS NULL;

ID	NOMBRE	APELLIDO
1	A1		A2
2	B1		B2
3	C1		C2
4	D1		D2
5	E1	    NULL
6	NULL	F2

------------------
CROSS JOIN (A X B)
------------------

ID  NOMBRE	APELLIDO
1	A1		A2
1	A1		B2
1	A1		C2
1	A1		D2
1	A1		F2
2	B1		A2
2	B1		B2
2	B1		C2
2	B1		D2
2	B1		F2
3	C1		A2
3	C1		B2
3	C1		C2
3	C1		D2
3	C1		F2
4	D1		A2
4	D1		B2
4	D1		C2
4	D1		D2
4	D1		F2
5	E1		A2
5	E1		B2
5	E1		C2
5	E1		D2
5	E1		F2

*/