DROP USER USUARIOJOIN CASCADE;
CREATE USER USUARIOJOIN IDENTIFIED BY 12345678;
GRANT CONNECT,RESOURCE,dba TO USUARIOJOIN;
GRANT UNLIMITED TABLESPACE TO USUARIOJOIN;
ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- INICIAR SESION CON EL USUARIO PROBANDO1
CONNECT USUARIOJOIN/12345678@LOCALHOST:1521/XEPDB1

CREATE TABLE A(
   ID           NUMBER(1,0) NOT NULL PRIMARY KEY,
   NOMBRE       CHAR(2)     NOT NULL,
   IDSUPERVISOR NUMBER(1,0)     NULL
);

INSERT INTO A(ID, NOMBRE, IDSUPERVISOR) VALUES (1, 'A', NULL);
INSERT INTO A(ID, NOMBRE, IDSUPERVISOR) VALUES (2, 'B', 1);
INSERT INTO A(ID, NOMBRE, IDSUPERVISOR) VALUES (3, 'C', 1);
INSERT INTO A(ID, NOMBRE, IDSUPERVISOR) VALUES (4, 'D', 2);
INSERT INTO A(ID, NOMBRE, IDSUPERVISOR) VALUES (5, 'E', 2);

/*
-------
TABLA A
-------

ID	NOMBRE	IDSUPERVISOR
1	A 	    NULL
2	B 		1
3	C 		1
4	D 		2
5	E 		2

---------
SELF JOIN
---------

SELECT A1.Nombre AS EMPLEADO, A2.Nombre AS SUPERVISOR
FROM A A1
JOIN A A2 ON A1.IDSUPERVISOR = A2.ID;

EMPLEADO	SUPERVIDOR
B 			A 
C 			A 
D 			B 
E 			B 


*/